# Generated by Django 3.1.2 on 2020-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='coordinates',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
